networks:
  mynet:

volumes:
  mydb:

services:
  nwdb:
    image: stackupiss/northwind-db:v1
    volumes:
    - mydb:/var/lib/mysql
    networks:
    - mynet
  nwapp:
    image: stackupiss/northwind-app:v1
    environment:
    - DB_HOST=nwdb
    - DB_USER=root
    - DB_PASSWORD=changeit
    ports:
    - 8000-8100:3000
    networks:
    - mynet
    depends_on:
    - nwdb