---
apiVersion: v1
kind: Namespace
metadata:
  name: minio

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minio
data:
  MINIO_ROOT_USER: root
  MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
  MINIO_DISTRIBUTED_NODES: minio-sts-{0...2}.minio-hsvc.minio.svc.cluster.local/data
  MINIO_API_PORT_NUMBER: "9000"
  MINIO_CONSOLE_PORT_NUMBER: "9090"

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
data:
  # rootroot
  MINIO_ROOT_PASSWORD: cm9vdHJvb3Q=
