---
apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: minio
spec:
  clusterIP: None
  selector:
    app: minio
    name: minio-po
  ports:
  - name: api-port
    port: 9000
  - name: console-port
    port: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio
spec:
  type: ClusterIP
  selector:
    app: minio
    name: minio-po
  ports:
  - name: api-port
    port: 9000
    targetPort: api-port
  - name: console-port
    port: 9090
    targetPort: console-port

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-sts
  namespace: minio
spec:
  serviceName: minio-hsvc
  replicas: 3
  selector:
    matchLabels:
      app: minio
      name: minio-po
  volumeClaimTemplates:
  - metadata:
      name: data-vol
    spec:
      storageClassName: do-block-storage 
      accessModes: 
      - ReadWriteOncePod
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      name: minio-po
      labels:
        app: minio
        name: minio-po
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: minio-container
        image: bitnami/minio:2025.4.22
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: minio-cm
        - secretRef:
            name: minio-secret
        ports:
        - name: api-port
          containerPort: 9000
        - name: console-port
          containerPort: 9090
        volumeMounts:
        - name: data-vol
          mountPath: /data

