--- 
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: db-pvc 
  namespace: myns 
spec:
  accessModes:
  - ReadWriteOncePod
  resources: 
    requests: 
      storage: 1Gi
  storageClassName: do-block-storage
