---
apiVersion: v1 
kind: Secret 
metadata: 
  name: bgg-secret 
  namespace: myns
  labels:
    app: bgg
data: 
  BGG_DB_PASSWORD: Y2hhbmdlaXQ= 

---
apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: bgg-cm 
  namespace: myns
  labels:
    app: bgg
data: 
  BGG_DB_USER: root 
  mysql.cnf: |
    # Copyright (c) 2015, 2025, Oracle and/or its affiliates.
    #
    # This program is free software; you can redistribute it and/or modify
    # it under the terms of the GNU General Public License, version 2.0,
    # as published by the Free Software Foundation.
    #
    # This program is designed to work with certain software (including
    # but not limited to OpenSSL) that is licensed under separate terms,
    # as designated in a particular file or component or in included license
    # documentation.  The authors of MySQL hereby grant you an additional
    # permission to link the program and your derivative works with the
    # separately licensed software that they have either included with
    # the program or referenced in the documentation.
    #
    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License, version 2.0, for more details.
    #
    # You should have received a copy of the GNU General Public License
    # along with this program; if not, write to the Free Software
    # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA

    #
    # The MySQL  Server configuration file.
    #
    # For explanations see
    # http://dev.mysql.com/doc/mysql/en/server-system-variables.html

  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local


--- 
apiVersion: v1 
kind: Pod 
metadata:
  name: fakeapi-po 
  namespace: myns
  labels:
    app: fakeapi 
spec:
  volumes:
  - name: secret-vol
    secret:
      secretName: bgg-secret
  - name: config-vol
    configMap:
      name: bgg-cm

  containers:
  - name: fakeapi-containers 
    image: chukmunnlee/fake-api:v1
    imagePullPolicy: IfNotPresent
    volumeMounts: 
    - name: secret-vol 
      mountPath: /opt/secrets
      readOnly: true
    - name: config-vol 
      mountPath: /opt/config

    ports:
    - name: fakeapi-port 
      containerPort: 3000
    resources: {}