--- 
apiVersion: v1 
kind: Pod 
metadata:
  name: dov-po 
  namespace: myns
  labels:
    app: dov 
spec:
  containers:
  - name: dov-containers 
    image: chukmunnlee/dov-bear:v5
    imagePullPolicy: IfNotPresent
    env:
    - name: INSTANCE_NAME
      value: 'hello, pod'
    - name: INSTANCE_HASH
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['app']
    ports:
    - name: dov-port 
      containerPort: 3000
    resources: {}