---
apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler
metadata: 
  name: dov-hpa 
  namespace: dov
spec: 
  minReplicas: 1 
  maxReplicas: 8
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: dov-deploy
  metrics:
  - type: Resource 
    resource: 
      name: memory
      target: 
        type: Utilization
        averageUtilization: 50
  - type: Resource 
    resource: 
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 30